// This file is auto-generated by next-intl, do not edit directly.
// See: https://next-intl.dev/docs/workflows/typescript#messages-arguments

declare const messages: {
  "header": {
    "logoLabel": "Homezup",
    "login": "Login",
    "join": "Join as Provider",
    "language": "Language",
    "openMenu": "Open menu",
    "closeMenu": "Close menu",
    "active": "active",
    "inactive": "inactive",
    "myProfile": "My Profile",
    "editProfile": "Edit Profile",
    "accountSettings": "Account Settings",
    "notifications": "Notifications",
    "security": "Security",
    "helpCenter": "Help Center",
    "services": "My Services",
    "account": "Account Settings",
    "help": "Help & Support",
    "logout": "Logout"
  },
  "nav": {
    "home": "Home",
    "services": "Services",
    "browse": "Browse Providers",
    "process": "How It Works",
    "contact": "Contact Us "
  },
  "hero": {
    "heading": "Find Trusted Home Service Providers In Your City",
    "paragraph": "Explore hundreds of real offers for cleaning, plumbing, repairs and more",
    "features": {
      "verifiedProfessionals": "Verified Professionals",
      "support": "24/7 Support",
      "rating": "4.8/5 Rating"
    },
    "search": {
      "selectService": "Select Service",
      "selectCity": "Select City",
      "searchNow": "Search Now",
      "searching": "Searching..."
    }
  },
  "browseByNeed": {
    "heading": "Browse by Need",
    "description": "Find the right professionals for any home service you need",
    "sectionAria": "Browse By Need, Find The Perfect Service Provider Fits For Your Job",
    "categories": {
      "c1": "Plumbing",
      "c2": "Electrical",
      "c3": "Cleaning",
      "c4": "AC Repair",
      "c5": "Painting",
      "c6": "Handyman",
      "c7": "Gardening",
      "c8": "Security",
      "c9": "Elderly Care",
      "c10": "Men's Salon Services",
      "c11": "Event Setup",
      "c12": "Babysitting",
      "c13": "Window & Glass",
      "c14": "Moving & Transport",
      "c16": "Appliance Repair",
      "c17": "Vehicle Cleaning",
      "c18": "Water Tank Cleaning",
      "c19": "Women's Salon",
      "c20": "Renovation",
      "c21": "Solar Panel Services",
      "c22": "Pest Control"
    }
  },
  "whatWeOffer": {
    "heading": "What We Offer",
    "description": "Professional services for every home need",
    "sectionButton": "View all Offers"
  },
  "latestOffers": {
    "heading": "Latest Offers from Providers",
    "description": "Latest service offers from verified providers",
    "sectionButton": "View all Offers"
  },
  "meetHelpers": {
    "heading": "Meet the Helper Behind the Hustle",
    "description": "Skilled professionals ready to help with your home needs",
    "sectionButton": "View all Offers"
  },
  "hhw": {
    "section": {
      "ariaLabel": "How Homezup Works Section",
      "heading": "How Homezup Works",
      "headingId": "latest-offers-heading",
      "description": "Simple steps to connect with trusted home service providers"
    },
    "steps": {
      "step1": {
        "step": "1",
        "title": "Search & Explore",
        "description": "Find trusted home-service providers by category or location",
        "ariaLabel": "Step 1: Search and Explore home service providers"
      },
      "step2": {
        "step": "2",
        "title": "Create Your Account",
        "description": "Sign up to message providers directly and get personalized updates.",
        "ariaLabel": "Step 2: Create your account on Homezup"
      },
      "step3": {
        "step": "3",
        "title": "Get it done",
        "description": "Message the chosen provider directly and let him handle the rest.",
        "ariaLabel": "Step 3: Get the service done by your chosen provider"
      },
      "arrow": {
        "ariaLabel": "Next Step"
      }
    }
  },
  "testimonials": {
    "headingStart": "Wall of",
    "headingEnd": "Customer Success",

    "t1": {
      "message": "Excellent service! The plumber arrived on time and fixed everything perfectly. Highly recommend!",
      "name": "Emma Wilson"
    },
    "t2": {
      "message": "Great platform! Found a reliable cleaner quickly and the booking process was seamless.",
      "name": "David Brown"
    },
    "t3": {
      "message": "Professional and trustworthy service providers. The verification system gives me peace of mind.",
      "name": "Lisa Chen"
    },
    "t4": {
      "message": "Excellent service! The plumber arrived on time and fixed everything perfectly. Highly recommend!",
      "name": "Emma Wilson"
    },
    "t5": {
      "message": "Great platform! Found a reliable cleaner quickly and the booking process was seamless.",
      "name": "David Brown"
    },
    "t6": {
      "message": "Professional and trustworthy service providers. The verification system gives me peace of mind.",
      "name": "Lisa Chen"
    }
  },
  "faq": {
    "section": {
      "heading": "Frequently Asked Questions",
      "headingAriaLabel": "Frequently Asked Questions",
      "description": "Find answers to common questions about Homezup's platform",
      "descriptionAriaLabel": "Find answers to common questions about Homezup's platform",
      "containerAriaLabel": "Frequently Asked Questions container",
      "headerAriaLabel": "Section header"
    },
    "toggle": {
      "groupAriaLabel": "Toggle between FAQs for Users and Providers",
      "user": {
        "label": "For Users",
        "ariaLabel": "Show FAQs for users"
      },
      "provider": {
        "label": "For Providers",
        "ariaLabel": "Show FAQs for providers"
      }
    },
    "accordion": {
      "itemAriaLabel": "FAQ item",
      "questionAriaLabel": "Question",
      "answerAriaLabel": "Answer"
    },
    "faqList": {
      "user": {
        "q1": {
          "question": "What is Homezup?",
          "answer": "Homezup is an online platform connecting you with trusted local service providers for home maintenance, cleaning, repairs, and more."
        },
        "q2": {
          "question": "Do I need to create an account?",
          "answer": "Yes, an account allows you to book services, track requests, and manage appointments easily."
        },
        "q3": {
          "question": "Are the providers verified?",
          "answer": "All providers go through a verification process to ensure reliability and quality."
        },
        "q4": {
          "question": "How do I book a service?",
          "answer": "Select the service you need, choose a provider, schedule a time, and confirm payment through the platform."
        }
      },
      "provider": {
        "q1": {
          "question": "How do I become a provider?",
          "answer": "Sign up on Homezup as a provider, submit your personal and business details, and complete the verification process to start offering your services."
        },
        "q2": {
          "question": "What services can I offer?",
          "answer": "You can offer any home-related services such as cleaning, electrical work, plumbing, AC repair, painting, and more. Make sure to specify your expertise during signup."
        },
        "q3": {
          "question": "Do I need to be verified?",
          "answer": "Yes, all providers must pass our verification process, which ensures trust and safety for users."
        },
        "q4": {
          "question": "How do I manage bookings?",
          "answer": "Providers can view, accept, or decline service requests from their dashboard, and update their availability in real time."
        }
      }
    },
    "contactSupport": {
      "label": "Contact Support",
      "ariaLabel": "Contact Support team"
    }
  },
  "postcard": {
    "heading": "Take Homezup with you",
    "description": "Get easy access to all services on the go with our mobile app. Book, track, andmanage your home services from anywhere, anytime.",
    "postCardAriaLabel": "Mobile app promotion section",
    "downloadInfoAriaLabel": "App download information and signup form",
    "message": "Coming soon to App Store and Google Play",
    "mobileAppAriaLabel": "Links to download the mobile app",
    "downloadOn": "Download on the",
    "appStore": "App Store",
    "appStoreAriaLabel": "Download Homezup app from the Apple App Store",
    "getIt": "Get It On",
    "googlePlay": "Google Play",
    "googlePlayAriaLabel": "Download Homezup app from Google Play",
    "emailMessage": "Get notified when we launch",
    "EmailSignupAriaLabel": "Email notification signup form",
    "inputPlaceholder": "Your Email Address",
    "inputAriaLabel": "Enter your email address to get launch notifications",
    "submitEmail": "Get Notified",
    "submitEmailAriaLabel": "Submit your email to get notified about the app launch",
    "decorativeLabel": "Illustration of the Homezup mobile app"
  },
  "cta": {
    "heading": "Ready to transform your home experience?",
    "description": "Join thousands of satisfied customers who trust Homezup for their home service needs",
    "BookService": "Book A Service",
    "BecomeProvider": "Become A Provider"
  },
  "footer": {
    "tagline": "Connecting you with trusted local service providers for all your home needs",
    "helpMessage": "Need help finding a service?",
    "copyright": "© 2025 Homezup. All rights reserved.",
    "forCustomers": {
      "title": "For Customers",
      "findServices": "Find Services",
      "browseProviders": "Browse Providers",
      "howItWorks": "How It Works",
      "safetyGuide": "Safety Guide",
      "faqs": "FAQs"
    },
    "forProviders": {
      "title": "For Providers",
      "joinAsProvider": "Join as Provider",
      "providerLogin": "Provider Login",
      "faqs": "FAQs"
    },
    "aboutHomezup": {
      "title": "About Homezup",
      "aboutUs": "About Us",
      "contactUs": "Contact Us",
      "cookiesPolicy": "Cookies Policy",
      "privacyPolicy": "Privacy Policy",
      "termsOfService": "Terms of Service"
    }
  },
  "privacyPolicy": {
    "title": "Privacy Policy",
    "subtitle": "At Homezup, your privacy is a priority. Here's how we handle your data with care and transparency.",
    "effectiveDate": "Effective from July 2025",
    "sections": {
      "whatWeCollect": {
        "title": "What Information We Collect",
        "users": {
          "title": "Users",
          "items": [
            "Device & browser data",
            "Name and email"
          ]
        },
        "providers": {
          "title": "Providers",
          "items": [
            "Full name, phone, city",
            "Services offered",
            "Profile photo",
            "Optional ID docs"
          ]
        },
        "warning": "⚠️ We don't store or process payments."
      },
      "howWeUse": {
        "title": "How We Use Your Data",
        "items": [
          "Match users with relevant providers",
          "Power listings and reviews",
          "Respond to support queries",
          "Showcase provider verification"
        ],
        "assurance": "🔒 We never sell or rent your data."
      },
      "communication": {
        "title": "Communication",
        "description": "Homezup may contact you via email or WhatsApp for service-related updates, booking confirmations, and important notifications.",
        "newsletter": "We only send newsletters if you've subscribed. You can manage your preferences in your account settings.",
        "unsubscribe": "You can unsubscribe from marketing emails at any time by clicking the unsubscribe link in any email or contacting us directly."
      },
      "cookies": {
        "title": "Cookies",
        "description": "We use cookies to personalize your experience, analyze site traffic, and improve our services. You can manage cookie preferences in your browser settings.",
        "linkText": "View our Cookies Policy"
      },
      "dataSecurity": {
        "title": "Data Security",
        "description": "Strong safeguards in place",
        "note": "Note: No platform can guarantee 100% security - but we do our best."
      },
      "yourRights": {
        "title": "Your Rights",
        "items": [
          "Request a copy of data",
          "Correct or delete profile info",
          "Deactivate account"
        ],
        "contact": "To exercise these rights, contact us at:"
      },
      "externalServices": {
        "title": "External Services",
        "description": "We may link to third-party tools (e.g., WhatsApp, Google Maps) to enhance your experience.",
        "clarification": "Homezup doesn't control their data policies - please review their privacy practices separately."
      },
      "policyUpdates": {
        "title": "Policy Updates",
        "description": "This policy may be updated from time to time. New versions will be published on this page with an updated effective date."
      },
      "contactUs": {
        "title": "Contact Us",
        "description": "Questions about cookies or privacy?",
        "email": "Email us at:"
      }
    }
  },
  "auth": {
    "authButtons": {
      "login": "Log in",
      "sign up": "Sign Up",
      "Continue as User": "Continue as User",
      "Continue as Provider": "Continue as Provider"
    },
    "login": {
      "email": "Email",
      "emailPlaceholder": "Enter your email",
      "password": "Password",
      "passwordPlaceholder": "Enter your password",
      "rememberMe": "Remember Me",
      "login": "Log In",
      "loggingIn": "Logging In",
      "forgotPassword": "Forgot Password?",
      "orContinueWith": "or Continue With",
      "continueWithGoogle": "Continue With Google",
      "continuingWithGoogle": "Continuing With Google"
    },
    "signup": {
      "firstName": "First Name",
      "firstNamePlaceholder": "Enter you first name",
      "lastName": "Last Name",
      "lastNamePlaceholder": "Enter you last name",
      "email": "Email Address",
      "emailPlaceholder": "Enter you email",
      "phoneNumber": "Phone Number (WhatsApp preferred)",
      "phoneNumberPlaceholder": "WhatsApp number",
      "password": "Password",
      "passwordPlaceholder": "Create a password",
      "confirmPassword": "Confirm Password",
      "confirmPasswordPlaceholder": "Confirm your password",
      "agree": "I agree to the",
      "terms": "Terms of Service",
      "privacy": "Privacy Policy",
      "signup": "Sign Up",
      "signingup": "Signing Up",
      "orContinueWith": "or Continue With",
      "alradyHaveAccount": " Already Have an account?",
      "loginHere": "Login here",
      "and": "and"
    },
    "userDecorator": {
      "heading": "Connect with Trusted Home Service Providers",
      "paragraph": " Find reliable professionals for all your home needs across Morocco"
    },
    "providerDecorator": {
      "heading": "Join Homezup as a Verified Provider",
      "paragraph": "Grow your business and connect with clients across Morocco."
    },
    "emailVerification": {
      "toastInitiated": "Email verification initiated. Please check your inbox.",
      "emailVerifiedTitle": "Email Verified!",
      "checkYourEmailTitle": "Check Your Email",
      "emailVerifiedMessage": "Your email has been successfully verified.",
      "checkYourEmailMessage": "We have sent a confirmation link to",
      "openEmailApp": "Open Email App",
      "resendVerification": "Resend Verification",
      "resending": "Resending...",
      "resendSuccess": "Verification email resent successfully!",
      "resendErrorDefault": "Something went wrong while resending the email.",
      "checkSpam": "Make sure to check your spam or promotions folder.",
      "didNotReceive": "Didn't receive the email?",
      "wrongEmail": "Wrong Email?",
      "goBackUpdate": "Go back and update your account details",
      "ariaMainLabel": "Email verification page",
      "ariaInstructionsLabel": "Email verification instructions",
      "ariaOpenEmailApp": "Open Gmail in a new tab"
    },
    "logout": {
      "ariaMainLabel": "Logout confirmation page",
      "ariaRegionLabel": "Logout confirmation section",

      "title": "Confirm Logout",
      "description": "Are you sure you want to log out? You'll need to sign in again to ",
      "accessYourAccount": "access your account.",

      "cancel": "Cancel",
      "confirmLogout": "Yes, Log Out"
    },
    "loggedOut": {
      "ariaMainLabel": "Log Out Successful Page",
      "ariaRegionLabel": "Logout success section",

      "title": "You've Been Logged Out",
      "description": "Your session has ended securely. Thank you for using our platform.",

      "goToLogin": "Go to Login"
    },
    "resetPassword": {
      "ariaMainLabel": "Reset password page",
      "ariaRegionLabel": "Reset password form",

      "title": "Reset Your Password",
      "description": "Enter your email address to receive a reset link",

      "emailLabel": "Email Address",
      "emailPlaceholder": "Enter your email",

      "emailValid": "Email format looks good",

      "buttonSending": "Sending...",
      "buttonSendLink": "Send Reset Link",

      "toastSuccess": "Reset link sent successfully!",
      "toastError": "Failed to send reset link.",
      "fallbackError": "Something went wrong. Try again.",

      "supportText": "Need help?",
      "supportEmail": "Contact support@homezup.ma",

      "backToLogin": "Back to Login",

      "decorTitle": "We'll help you get back into your account safely"
    },
    "verificationSuccessful": {
      "ariaMainLabel": "Email verification success page",
      "title": "Email Verified Successfully",
      "description": " Your account has been activated. You can now log  in and start connecting with clients across Morocco.",
      "goToLogin": "Go to Login",
      "return": "Return to Homezup homepage"
    },
    "profileSetup": {
      "steps": {
        "step1": "Account Created",
        "step2": "Set Up Profile"
      },
      "heading": "Let's finish setting up your profile!",
      "description": "Tell us about your services to attract more customers",
      "form": {
        "serviceCategory": {
          "label": "Service Category",
          "placeholder": "Select your service category"
        },
        "serviceTitle": {
          "label": "Service Title",
          "placeholder": "e.g., Expert Electrician in Casablanca"
        },
        "yearsExperience": {
          "label": "Years of Experience",
          "placeholder": "5"
        },
        "city": {
          "label": "City/Coverage Area",
          "placeholder": "Select your city"
        },
        "fullAddress": {
          "label": "Address",
          "placeholder": ""
        },
        "startingPrice": {
          "label": "Starting Price (MAD)",
          "placeholder": "200"
        },
        "bio": {
          "label": "Short Bio",
          "placeholder": "Tell customers about your experience..."
        },
        "profilePhoto": {
          "label": "Profile Photo",
          "info": "JPG, PNG up to 5MB",
          "clickToUpload": "Click to upload your profile photo"
        },
        "portfolioImages": {
          "label": "Portfolio Images (Up to 3)",
          "uploadImage": "Upload Image "
        },
        "submitButton": "Complete Profile",
        "formError": "Please fix the errors above before submitting",
        "infoText": "You can always edit this information later from your dashboard"
      },
      "uploadPhotos": "Upload Photos"
    },
    "errors": {
      "required": "{field} is required",
      "invalidEmail": "Please enter a valid email",
      "maxLength": "{field} cannot exceed {max} characters",
      "invalidNumber": "Please enter a valid number"
    }
  },
  "services": {
    "hero": {
      "title": "Find HomeServices in Morocco",
      "description": "Browse through our wide range of professional home services",
      "search": {
        "category": "All Categories",
        "city": "All Cities",
        "price": "any",
        "filter": "Filter"
      }
    },
    "sectionButton": "View All",
    "service": {
      "share": "Share",
      "description": "Service Description",
      "included": "What's Included",
      "notIncluded": "What's Not Included",
      "supplies": "Supplies & Equipment",
      "review": {
        "title": "What Others Say",
        "seeAll": "See all",
        "reviews": "reviews"
      },
      "contact": {
        "call": "Call",
        "message": "Message",
        "whatsapp": "WhatsApp",
        "report": "Report"
      },
      "relatedServices": "You Might Also Like"
    }
  },
  "browseProviders": {
    "hero": {
      "title": "Top-Rated Providers Near You",
      "description": "Find trusted professionals for your home — rated by real customers.",
      "findExperts": "Find Experts",
      "filters": {
        "category": "All Categories",
        "city": "Select City",
        "priceRange": "Price Range",
        "minimumRating": "Minimum Rating"
      }
    },
    "topRated": {
      "title": "Top Rated Providers",
      "viewAll": "View All",
      "noProviders": "No top rated providers found"
    },
    "allProviders": {
      "title": "All Providers",
      "verifiedOnly": "Verified Only",
      "sortBy": "Newest First",
      "loading": "Loading providers...",
      "noProviders": "No providers found",
      "tryAdjusting": "Try adjusting your filters or search criteria."
    }
  },
  "status": {
    "loading": {
      "title": "Hang tight, we're loading your experience...",
      "description": "Finding the best providers near you"
    },
    "notFound": {
      "title": "Oops! We couldn't find that page.",
      "retry": "Retry",
      "returnHome": "Return Home",
      "contactSupport": "Contact Support",
      "helpCenter": "Help Center",
      "emailUs": "Email Us",
      "copyright": "© 2025 Homezup. We'll get this fixed faster than you can say 'wrench'!",
      "chatSupport": "Chat Support",
      "help": "We'll be back soon to help!"
    },
    "noInternet": {
      "title": " You're offline",
      "description": "Please check your internet connection",
      "tryAgain": "Try Again"
    },
    "maintenance": {
      "title": "We're Improving Your Experience!",
      "description": "Homezup is currently undergoing scheduled maintenance.",
      "estimatedTime": "Estimated time to return:",
      "retry": "Retry",
      "returnHome": "Return Home",
      "contactSupport": "Contact Support",
      "helpCenter": "Help Center",
      "emailUs": "Email Us",
      "copyright": "© 2025 Homezup. We'll get this fixed faster than you can say 'wrench'!",
      "chatSupport": "Chat Support",
      "help": "We'll be back soon to help!"
    },
    "errorPage": {
      "toast": "Something went wrong!",
      "statusCode": "500 Server Error",
      "defaultHeading": "Something went wrong on our end",
      "description": "We're fixing the issue. Please try again in a moment",
      "retry": "Retry",
      "home": "Home"
    }
  },
  "providersDashboard": {
    "profile": {
      "reviews": "reviews",
      "memberSince": "Member since",
      "edit": "Edit Profile",
      "view": "View Public Profile",
      "requestVerification": "Request Verification",
      "profileCompletion": "Profile Completion",
      "complete": "complete"
    },
    "performances": {
      "title": "Your Performance",
      "actionButton": "Boost Visibility",
      "titles": {
        "t1": "Profile Views",
        "t2": "Message Received",
        "t3": "Contact Clicks"
      },
      "thisWeek": "This Week"
    },
    "myServices": {
      "title": "My Services",
      "addNewService": "Add New Service"
    },
    "portfolio": {
      "title": "Portfolio",
      "addPhotos": "Add Photos",
      "addPhoto": "Add Photo"
    },
    "featureCommingSoon": {
      "title": "Exciting Features Coming Soon!",
      "description1": "We're working on tools like booking calendars, premium visibility, and payment tracking to help ",
      "description2": "you grow your business.",
      "actionButton": "Get Notified"
    },
    "editProfileModal": {
      "title": "Edit Profile",
      "description": "Keep your information up to date so clients can find and trust you.",
      "profileCompletion": {
        "label": "Profile {percent}% complete",
        "ariaLabel": "Profile completion {percent} percent"
      },
      "sections": {
        "profileInformation": {
          "heading": "Profile Information",
          "changePhoto": "Change Photo",
          "avatarTip": "Add a photo — profiles with pictures get 3x more views"
        },
        "basicInfo": {
          "fullName": "Full Name / Business Name",
          "fullNamePlaceholder": "e.g. Youssef Plumbing Services",
          "profession": "Profession / Category",
          "professionPlaceholder": "Select profession",
          "bio": "Bio / About Me",
          "bioPlaceholder": "Describe your experience and what makes you unique"
        },
        "locationExperience": {
          "city": "City / Location",
          "cityPlaceholder": "Select your city",
          "serviceArea": "Service Coverage Area",
          "serviceAreaPlaceholder": "e.g. Within 20km of city center",
          "experience": "Years of Experience",
          "experiencePlaceholder": "e.g. 5",
          "startingPricePlaceholder": "Enter your starting price"
        },
        "languages": {
          "label": "Languages Spoken",
          "addButton": "Add",
          "inputPlaceholder": "Type a language...",
          "dropdownAriaLabel": "Add or search for a language",
          "suggestionsAriaLabel": "Language suggestions"
        },
        "contactMethods": {
          "heading": "Contact Methods",
          "phone": "Phone Number",
          "phonePlaceholder": "+8801XXXXXXXXX",
          "whatsapp": "WhatsApp Number (Optional)",
          "whatsappPlaceholder": "+8801XXXXXXXXX",
          "email": "Email Address",
          "emailPlaceholder": "you@example.com"
        },
        "professionalDetails": {
          "heading": "Professional Details",
          "uploadPortfolio": "Upload Portfolio/Work Image",
          "dragDropTip": "Drag and drop files here or click to browse",
          "formatsTip": "PDF, JPG, PNG up to 10MB",
          "uploadImage": "Upload Image {index}"
        }
      },
      "buttons": {
        "cancel": "Cancel",
        "saveChanges": "Save Changes",
        "saving": "Saving..."
      },
      "validation": {
        "imageFormatCorrect": "Image format is correct"
      }
    },
    "serviceModal": {
      "titleAdd": "Add New Service",
      "titleEdit": "Edit Service",

      "fields": {
        "title": "Service Title",
        "titlePlaceholder": "e.g., Electrical Installation",

        "category": "Category",
        "categoryPlaceholder": "Select category",

        "city": "City",
        "cityPlaceholder": "Select city",

        "description": "Short Description",
        "descriptionPlaceholder": "Describe your service...",

        "startingPrice": "Starting Price",
        "startingPricePlaceholder": "0",
        "startingPriceSuccess": "Price format is correct",

        "currency": "MAD"
      },

      "status": {
        "label": "Service Status",
        "active": "Active",
        "inactive": "Inactive",
        "activeDesc": "Service visible to clients",
        "inactiveDesc": "Service hidden"
      },

      "images": {
        "label": "Service Images",
        "dropText": "Drop images here or click to upload",
        "note": "Maximum 4 images • JPG, PNG up to 5MB each",
        "chooseFile": "Choose File",
        "tip": "💡 Add a photo to get more profile views!",
        "alt": "Service Image {index}"
      },

      "buttons": {
        "cancel": "Cancel",
        "save": "Save Service"
      }
    }
  }
};
export default messages;